name: Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Rodar testes com cobertura
        run: dotnet test ./AnimeRecommender.Tests/AnimeRecommender.Tests.csproj --no-build --collect:"XPlat Code Coverage"

      - name: Enviar cobertura pro Codecov
        uses: codecov/codecov-action@v4
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # Não precisa se repo for público
          files: '**/coverage.cobertura.xml'
          flags: unittests
          name: codecov-report
